

#\u7AEF\u53E3
server:
  port: 8080
  servlet:
    context-path: /api/


#mybatis \u6570\u636E\u6E90\u7B49

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

